POST http://localhost:3000/courses
Content-Type: application/json

{
    "name": "Cloud Computing",
    "ects": 6,
    "semester": 5,
    "degreeProgramID": 1,
    "type": "ELECTIVE"
}
### Alle Courses
GET http://localhost:3000/courses

### Get ein Course nach einer gegebener ID
GEt http://localhost:3000/courses/18

### get all enrollments from a student 
GET http://localhost:3000/students/1/enrollments

### get all finished enrollments from a studeent
GET http://localhost:3000/students/1/enrollments/finished

### Abgeschlossene ECTS eines Studenten
GET http://localhost:3000/students/1/ects/completed

### returns the remaining etcs form a student 
GET http://localhost:3000/students/1/ects/remaining

### Gets the percentage of the finishees etcs from a given student
GET http://localhost:3000/students/1/progress

###  get all enrollments
GET http://localhost:3000/enrollments

### Delete given Enrolment
DELETE http://localhost:3000/enrollment/4/delete

### Update grade from a given enrollment
PATCH http://localhost:3000/enrollment/1/grade
Content-Type: application/json

{
    "grade": 3
}

### Try to update a grade from a not Finisched enrollment
PATCH http://localhost:3000/enrollment/5/grade
Content-Type: application/json

{
    "grade": 3
}

###