POST http://localhost:3000/courses
Content-Type: application/json

{
    "name": "ERP-Systeme",
    "ects": 6,
    "semester": 5,
    "degreeProgramID": 1,
    "type": "ELECTIVE"
}
### Alle Courses
GET http://localhost:3000/courses

### Get ein Course nach einer gegebener ID
GEt http://localhost:3000/courses/2

### get all enrollments from a student 
GET http://localhost:3000/students/1/enrollments

### get all finished enrollments from a studeent
GET http://localhost:3000/students/1/enrollments/finished

### returns the completed etcs from a student
GET http://localhost:3000/students/1/ects/completed

### returns the remaining etcs form a student 
GET http://localhost:3000/students/1/ects/remaining

### Gets the percentage of the finishees etcs from a given student
GET http://localhost:3000/students/1/progress

###  get all enrollments
GET http://localhost:3000/enrollments

### Delete given Enrolment
DELETE http://localhost:3000/enrollment/4/delete

### Update grade from a given enrollment
PATCH http://localhost:3000/enrollment/1/grade
Content-Type: application/json

{
    "grade": 3
}

### Try to update a grade from a not Finisched enrollment
PATCH http://localhost:3000/enrollment/5/grade
Content-Type: application/json

{
    "grade": 3
}

### GET ALL STUDENT

GET http://localhost:3000/students/

###
GET http://localhost:3000/students/6

###
POST http://localhost:3000/students/
Content-Type: application/json

{
    "firstName": "Zorro",
    "lastName": "Ronoroa"
}

### delete a student
DELETE http://localhost:3000/students/5

### get the degree Progamm from a given student
GET http://localhost:3000/students/4/degree-program


### assign a degree Programm to a student

PUT http://localhost:3000/students/7/degree-program/5

### Edit a course
PUT http://localhost:3000/courses/16
Content-Type: application/json

{
    "name": "ERP-Systeme",
    "ects": 6,
    "semester": 5,
    "degreeProgramID": 1,
    "type": "VOLUNTARY"
}

### Delete a course
DELETE http://localhost:3000/courses/16

### Get all courses from a degreeProgramm
GET http://localhost:3000/courses/degree-program/2

### Get all degree programs

GET http://localhost:3000/degreePrograms/